terminal = "ghostty" 
logseq = "flatpak run --socket=wayland com.logseq.Logseq --ozone-platform-hint=auto     --enable-features=WaylandWindowDecorations"
emacs = "emacsclient -c" 
fileManager = "thunar"
browser = "zen-browser"
org_capture = "~/.config/emacs/bin/org-capture"
menu = "fuzzel"
cmenu = "~/.config/fuzzel/scripts/command-menu"
music = "Cider --enable-features=UseOzonePlatform --ozone-platform=wayland"
