hl.on("hyprland.start", function ()  
 hl.exec_cmd("fnott")
 hl.exec_cmd("clipse -listen")
 hl.exec_cmd("systemctl --user import-environment WAYLAND_DISPLAY XDG_RUNTIME_DIR DISPLAY")
 hl.exec_cmd("hypridle")
 hl.exec_cmd("hyprpaper")
 hl.exec_cmd("waybar")
 hl.exec_cmd("systemctl --user start hyprpolkitagent")
 hl.exec_cmd("dbus-update-activation-environment --systemd --all")
end)
