palette = "catppuccin_mocha"
format = """
[](blue)\
[ 󰀄 ](bg:blue fg:base)\
$username\
[](bg:teal fg:blue)\
$directory\
[](fg:teal bg:peach)\
$git_branch\
$git_status\
[](fg:peach bg:lavender)\
$c\
$elixir\
$elm\
$golang\
$haskell\
$java\
$julia\
$nodejs\
$nim\
$rust\
[](fg:lavender bg:green)\
$docker_context\
[](fg:green bg:blue)\
$time\
[ ](fg:blue)\
"""

# Disable the blank line at the start of the prompt
# add_newline = false

# You can also replace your username with a neat symbol like  to save some space
[username]
show_always = true
style_user = "fg:base bg:blue"
style_root = "fg:base bg:red"
format = '[$user ]($style)'

[directory]
style = "fg:base bg:teal"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
# Keep in mind that the order matters. For example:
# "Important Documents" = "  "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important  " = "  "

[c]
symbol = " "
style = "fg:base bg:mauve"
format = '[[ $symbol ($version) ](fg:base bg:mauve)]($style)'

[docker_context]
symbol = " "
style = "fg:base bg:green"
format = '[[ $symbol $context ](fg:base bg:green)]($style) $path'

[elixir]
symbol = " "
style = "fg:base bg:mauve"
format = '[[ $symbol ($version) ](fg:base bg:mauve)]($style)'

[elm]
symbol = " "
style = "fg:base bg:mauve"
format = '[[ $symbol ($version) ](fg:base bg:mauve)]($style)'

[git_branch]
symbol = ""
style = "fg:base bg:peach"
format = '[[ $symbol $branch ](fg:base bg:peach)]($style)'

[git_status]
style = "fg:base bg:peach"
format = '[[($all_status$ahead_behind )](fg:base bg:peach)]($style)'

[golang]
symbol = " "
style = "fg:base bg:mauve"
#format = '[[ $symbol ($version) ](fg:base bg:mauve)]($style)'
format = '[[ $symbol](fg:base bg:mauve)]($style)'
[haskell]
symbol = " "
style = "fg:base bg:mauve"
format = '[[ $symbol ($version) ](fg:base bg:mauve)]($style)'

[java]
symbol = " "
style = "fg:base bg:mauve"
format = '[[ $symbol ($version) ](fg:base bg:mauve)]($style)'

[julia]
symbol = " "
style = "fg:base bg:mauve"
format = '[[ $symbol ($version) ](fg:base bg:mauve)]($style)'

[nodejs]
symbol = ""
style = "fg:base bg:mauve"
format = '[[ $symbol ($version) ](fg:base bg:mauve)]($style)'

[nim]
symbol = " "
style = "fg:base bg:mauve"
format = '[[ $symbol ($version) ](fg:base bg:mauve)]($style)'

[rust]
symbol = ""
style = "fg:base bg:mauve"
format = '[[ $symbol ($version) ](fg:base bg:mauve)]($style)'

[time]
disabled = true
time_format = "%R" # Hour:Minute Format
style = "fg:base bg:blue"
format = '[  $time]($style)'

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"
